//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lively.UI.Wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lively.UI.Wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online discussion forum.
        /// </summary>
        public static string DescCommunity {
            get {
                return ResourceManager.GetString("DescCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API documentation and help.
        /// </summary>
        public static string DescDocumentation {
            get {
                return ResourceManager.GetString("DescDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively has encountered a fatal error.
        ///
        ///Windows Explorer restarted twice in the last 30 seconds! This may be a conflict between Lively and other desktop customization software or Windows. To avoid further issues, all wallpapers are terminated..
        /// </summary>
        public static string DescExplorerCrash {
            get {
                return ResourceManager.GetString("DescExplorerCrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible program found, taskbar theming disabled..
        /// </summary>
        public static string DescIncompatibleTaskbarTheme {
            get {
                return ResourceManager.GetString("DescIncompatibleTaskbarTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official webpage of Lively Wallpaper.
        /// </summary>
        public static string DescOfficialWebpage {
            get {
                return ResourceManager.GetString("DescOfficialWebpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most modern LCD and LED displays do not suffer from burn-in issue and therefore any wallpaper can be used as screensaver.
        ///
        ///For OLED, Plasma or CRT displays which are susceptibe to burn-in it is advised to use wallpaper with regular motion and an overall dark theme which is supposed to mitigate burn-in but this feature is untested and its effectiveness cannot be guaranteed.
        ///
        ///The main purpose of Lively&apos;s screensavers is to add another layer of customization to your pc, use screensavers as burn-in protecti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescOledScreensaverNotice {
            get {
                return ResourceManager.GetString("DescOledScreensaverNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a problem with the software.
        /// </summary>
        public static string DescReportBug {
            get {
                return ResourceManager.GetString("DescReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file or specify a website url to set as a wallpaper..
        /// </summary>
        public static string DescriptionAddWallpaper {
            get {
                return ResourceManager.GetString("DescriptionAddWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper playback behaviour based on running application..
        /// </summary>
        public static string DescriptionAppRules {
            get {
                return ResourceManager.GetString("DescriptionAppRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        public static string DescriptionCancelQuestion {
            get {
                return ResourceManager.GetString("DescriptionCancelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete this wallpaper from the disk?.
        /// </summary>
        public static string DescriptionDeleteConfirmation {
            get {
                return ResourceManager.GetString("DescriptionDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this wallpaper from the Library?.
        /// </summary>
        public static string DescriptionDeleteConfirmationLibrary {
            get {
                return ResourceManager.GetString("DescriptionDeleteConfirmationLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply drag and drop files into Library..
        /// </summary>
        public static string DescriptionDragDropFIle {
            get {
                return ResourceManager.GetString("DescriptionDragDropFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are opening an external application as wallpaper.
        ///Malicious applications can host malware, virus.. and do harm to your system.
        ///Only continue if this application comes from a trusted source..
        /// </summary>
        public static string DescriptionExternalAppWarning {
            get {
                return ResourceManager.GetString("DescriptionExternalAppWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively is minimized to systemtray, right click lively icon to continue..
        /// </summary>
        public static string DescriptionMinimizedTray {
            get {
                return ResourceManager.GetString("DescriptionMinimizedTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Lively for settings to take effect..
        /// </summary>
        public static string DescriptionPleaseRestartLively {
            get {
                return ResourceManager.GetString("DescriptionPleaseRestartLively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop before proceeding..
        /// </summary>
        public static string DescriptionPleaseStop {
            get {
                return ResourceManager.GetString("DescriptionPleaseStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to begin recording..
        /// </summary>
        public static string DescriptionRecordStart {
            get {
                return ResourceManager.GetString("DescriptionRecordStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently restoring previous wallpaper(s), please wait....
        /// </summary>
        public static string DescriptionRestoringWallpaper {
            get {
                return ResourceManager.GetString("DescriptionRestoringWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Display.
        /// </summary>
        public static string DescriptionScreenLayout {
            get {
                return ResourceManager.GetString("DescriptionScreenLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of software is available!.
        /// </summary>
        public static string DescriptionUpdateAvailable {
            get {
                return ResourceManager.GetString("DescriptionUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter website link to load, shadertoy.com shader links are supported.
        /// </summary>
        public static string DescriptionWebpageLoad {
            get {
                return ResourceManager.GetString("DescriptionWebpageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will get you started on setting up Lively..
        /// </summary>
        public static string DescriptionWelcomeWizard {
            get {
                return ResourceManager.GetString("DescriptionWelcomeWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Windows N/KN version will require the download of additional codecs to support video playback in wallpapers..
        /// </summary>
        public static string DescriptionWindowsNCodecInstall {
            get {
                return ResourceManager.GetString("DescriptionWindowsNCodecInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show support by buying the developer coffee.
        /// </summary>
        public static string DescSupperDev {
            get {
                return ResourceManager.GetString("DescSupperDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to change to beta (developer) build of Lively.
        ///Updates will be frequent and may contain bugs!.
        /// </summary>
        public static string DescSwitchBranchBetaWarning {
            get {
                return ResourceManager.GetString("DescSwitchBranchBetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update; try downloading the installer from:
        ///https://github.com/rocksdanister/lively/releases.
        /// </summary>
        public static string LivelyExceptionAppUpdateFail {
            get {
                return ResourceManager.GetString("LivelyExceptionAppUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged wallpaper file, try redownloading..
        /// </summary>
        public static string LivelyExceptionDamagedZipFile {
            get {
                return ResourceManager.GetString("LivelyExceptionDamagedZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops... Looks like something went wrong :(
        ///In order to better understand this error and fix the issue, share the log file with the developer.
        ///Instructions for sharing log file:
        ///https://github.com/rocksdanister/lively/wiki.
        /// </summary>
        public static string LivelyExceptionGeneral {
            get {
                return ResourceManager.GetString("LivelyExceptionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively cannot work properly with Windows High Contrast mode enabled!
        ///Disable High Contrast mode and try again..
        /// </summary>
        public static string LivelyExceptionHighContrastMode {
            get {
                return ResourceManager.GetString("LivelyExceptionHighContrastMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media playback failed :(
        ///Try changing the videoplayer in lively settings.
        ///
        ///In order to better understand this error and fix the issue, share the log file with the developer.
        ///Instructions for sharing log file:
        ///https://github.com/rocksdanister/lively/wiki.
        /// </summary>
        public static string LivelyExceptionMediaPlayback {
            get {
                return ResourceManager.GetString("LivelyExceptionMediaPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Lively wallpaper file..
        /// </summary>
        public static string LivelyExceptionNotLivelyZip {
            get {
                return ResourceManager.GetString("LivelyExceptionNotLivelyZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively was not closed properly, starting in safe mode.
        ///Do you wish to restore previously running wallpapers?.
        /// </summary>
        public static string LivelyExceptionSafeModeStart {
            get {
                return ResourceManager.GetString("LivelyExceptionSafeModeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like some settings need to be set to make Lively work:  
        ///1. Press the Win + R keys to open Run, 
        ///2. Type SystemPropertiesPerformance.exe into Run, click on &quot;OK&quot; to open Performance Options.
        ///3. Enable/Check &quot;Animate controls and elements inside windows&quot; (If already checked, then uncheck and check) &amp; Apply.
        ///4. Click &quot;Apply&quot; then press &quot;OK&quot; to close the window.
        ///
        ///If Windows 7 just set - Adjust for best appearance &amp;amp; Apply.
        ///If still not working, close &amp; start Lively again/restart windows.
        ///(Do [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LivelyExceptionWorkerWSetupFail {
            get {
                return ResourceManager.GetString("LivelyExceptionWorkerWSetupFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TextAdd {
            get {
                return ResourceManager.GetString("TextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string TextAllFiles {
            get {
                return ResourceManager.GetString("TextAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string TextApplication {
            get {
                return ResourceManager.GetString("TextApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribution.
        /// </summary>
        public static string TextAttribution {
            get {
                return ResourceManager.GetString("TextAttribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string TextAuthor {
            get {
                return ResourceManager.GetString("TextAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TextBack {
            get {
                return ResourceManager.GetString("TextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string TextBrowse {
            get {
                return ResourceManager.GetString("TextBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextCancel {
            get {
                return ResourceManager.GetString("TextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Wallpapers.
        /// </summary>
        public static string TextChangeWallpaper {
            get {
                return ResourceManager.GetString("TextChangeWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string TextClose {
            get {
                return ResourceManager.GetString("TextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Wallpapers.
        /// </summary>
        public static string TextCloseWallpapers {
            get {
                return ResourceManager.GetString("TextCloseWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        public static string TextCompleted {
            get {
                return ResourceManager.GetString("TextCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to manage wallpapers..
        /// </summary>
        public static string TextControlPanelOpen {
            get {
                return ResourceManager.GetString("TextControlPanelOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Video.
        /// </summary>
        public static string TextConvertVideo {
            get {
                return ResourceManager.GetString("TextConvertVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Preview.
        /// </summary>
        public static string TextCreatePreview {
            get {
                return ResourceManager.GetString("TextCreatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customise.
        /// </summary>
        public static string TextCustomise {
            get {
                return ResourceManager.GetString("TextCustomise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customise Wallpaper.
        /// </summary>
        public static string TextCustomiseWallpaper {
            get {
                return ResourceManager.GetString("TextCustomiseWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TextDeleteWallpaper {
            get {
                return ResourceManager.GetString("TextDeleteWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TextDescription {
            get {
                return ResourceManager.GetString("TextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Screen.
        /// </summary>
        public static string TextDisplayPauseRuleAllScreen {
            get {
                return ResourceManager.GetString("TextDisplayPauseRuleAllScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Screen.
        /// </summary>
        public static string TextDisplayPauseRulePerScreen {
            get {
                return ResourceManager.GetString("TextDisplayPauseRulePerScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string TextDownload {
            get {
                return ResourceManager.GetString("TextDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TextEditWallpaper {
            get {
                return ResourceManager.GetString("TextEditWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TextError {
            get {
                return ResourceManager.GetString("TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TextExit {
            get {
                return ResourceManager.GetString("TextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export lively .zip.
        /// </summary>
        public static string TextExportWallpaperZip {
            get {
                return ResourceManager.GetString("TextExportWallpaperZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some features are not available in this version of Lively..
        /// </summary>
        public static string TextFeatureMissing {
            get {
                return ResourceManager.GetString("TextFeatureMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string TextFileNotFound {
            get {
                return ResourceManager.GetString("TextFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated GIF.
        /// </summary>
        public static string TextGIF {
            get {
                return ResourceManager.GetString("TextGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show some love by dropping a star.
        /// </summary>
        public static string TextGitHubStar {
            get {
                return ResourceManager.GetString("TextGitHubStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GO.
        /// </summary>
        public static string TextGo {
            get {
                return ResourceManager.GetString("TextGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help translate.
        /// </summary>
        public static string TextHelpTranslate {
            get {
                return ResourceManager.GetString("TextHelpTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s).
        /// </summary>
        public static string TextHours {
            get {
                return ResourceManager.GetString("TextHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string TextInstall {
            get {
                return ResourceManager.GetString("TextInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string TextKeyboard {
            get {
                return ResourceManager.GetString("TextKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last checked.
        /// </summary>
        public static string TextLastChecked {
            get {
                return ResourceManager.GetString("TextLastChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string TextLearnMore {
            get {
                return ResourceManager.GetString("TextLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string TextLicense {
            get {
                return ResourceManager.GetString("TextLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minute(s).
        /// </summary>
        public static string TextMinutes {
            get {
                return ResourceManager.GetString("TextMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TextmoreInfo {
            get {
                return ResourceManager.GetString("TextmoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Wallpapers.
        /// </summary>
        public static string TextMoreWallpapers {
            get {
                return ResourceManager.GetString("TextMoreWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string TextMouse {
            get {
                return ResourceManager.GetString("TextMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse interaction when application focused.
        /// </summary>
        public static string TextMouseInteractOnDesktop {
            get {
                return ResourceManager.GetString("TextMouseInteractOnDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TextNext {
            get {
                return ResourceManager.GetString("TextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TextNo {
            get {
                return ResourceManager.GetString("TextNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string TextOff {
            get {
                return ResourceManager.GetString("TextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string TextOK {
            get {
                return ResourceManager.GetString("TextOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string TextOn {
            get {
                return ResourceManager.GetString("TextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string TextOnline {
            get {
                return ResourceManager.GetString("TextOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Lively.
        /// </summary>
        public static string TextOpenLively {
            get {
                return ResourceManager.GetString("TextOpenLively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Process.
        /// </summary>
        public static string TextPauseAlgoAllProcess {
            get {
                return ResourceManager.GetString("TextPauseAlgoAllProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct3D.
        /// </summary>
        public static string TextPauseAlgoExclusiveMode {
            get {
                return ResourceManager.GetString("TextPauseAlgoExclusiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Process.
        /// </summary>
        public static string TextPauseAlgoForegroundProcess {
            get {
                return ResourceManager.GetString("TextPauseAlgoForegroundProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Wallpapers.
        /// </summary>
        public static string TextPauseWallpapers {
            get {
                return ResourceManager.GetString("TextPauseWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        public static string TextPerformanceKill {
            get {
                return ResourceManager.GetString("TextPerformanceKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string TextPerformanceNone {
            get {
                return ResourceManager.GetString("TextPerformanceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string TextPerformancePause {
            get {
                return ResourceManager.GetString("TextPerformancePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string TextPicture {
            get {
                return ResourceManager.GetString("TextPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string TextPreviewWallpaper {
            get {
                return ResourceManager.GetString("TextPreviewWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string TextPrivacyPolicy {
            get {
                return ResourceManager.GetString("TextPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string TextProcessingWallpaper {
            get {
                return ResourceManager.GetString("TextProcessingWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TextRemove {
            get {
                return ResourceManager.GetString("TextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string TextRule {
            get {
                return ResourceManager.GetString("TextRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string TextScreen {
            get {
                return ResourceManager.GetString("TextScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string TextSearch {
            get {
                return ResourceManager.GetString("TextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Wallpaper.
        /// </summary>
        public static string TextSetWallpaper {
            get {
                return ResourceManager.GetString("TextSetWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Location.
        /// </summary>
        public static string TextShowOnDisk {
            get {
                return ResourceManager.GetString("TextShowOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string TextSource {
            get {
                return ResourceManager.GetString("TextSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TextStop {
            get {
                return ResourceManager.GetString("TextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you enjoy using Lively? Leave a review :).
        /// </summary>
        public static string TextStoreReview {
            get {
                return ResourceManager.GetString("TextStoreReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string TextSupport {
            get {
                return ResourceManager.GetString("TextSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to beta (Dev channel).
        /// </summary>
        public static string TextSwitchBranchDev {
            get {
                return ResourceManager.GetString("TextSwitchBranchDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to stable (Default channel).
        /// </summary>
        public static string TextSwitchBranchOfficial {
            get {
                return ResourceManager.GetString("TextSwitchBranchOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TextTags {
            get {
                return ResourceManager.GetString("TextTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blur.
        /// </summary>
        public static string TextTaskbarThemeBlur {
            get {
                return ResourceManager.GetString("TextTaskbarThemeBlur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string TextTaskbarThemeClear {
            get {
                return ResourceManager.GetString("TextTaskbarThemeClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string TextTaskbarThemeColor {
            get {
                return ResourceManager.GetString("TextTaskbarThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent.
        /// </summary>
        public static string TextTaskbarThemeFluent {
            get {
                return ResourceManager.GetString("TextTaskbarThemeFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string TextTaskbarThemeWallpaper {
            get {
                return ResourceManager.GetString("TextTaskbarThemeWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Fluent.
        /// </summary>
        public static string TextTaskbarThemeWallpaperFluent {
            get {
                return ResourceManager.GetString("TextTaskbarThemeWallpaperFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string TextTileSizeLarge {
            get {
                return ResourceManager.GetString("TextTileSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TextTileSizeNormal {
            get {
                return ResourceManager.GetString("TextTileSizeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string TextTileSizeSmall {
            get {
                return ResourceManager.GetString("TextTileSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headless.
        /// </summary>
        public static string TextUIHeadless {
            get {
                return ResourceManager.GetString("TextUIHeadless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite.
        /// </summary>
        public static string TextUILite {
            get {
                return ResourceManager.GetString("TextUILite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TextUINormal {
            get {
                return ResourceManager.GetString("TextUINormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format not supported.
        /// </summary>
        public static string TextUnsupportedFile {
            get {
                return ResourceManager.GetString("TextUnsupportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        public static string TextUpdateAvailable {
            get {
                return ResourceManager.GetString("TextUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string TextUpdateCheck {
            get {
                return ResourceManager.GetString("TextUpdateCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check for software update.
        /// </summary>
        public static string TextupdateCheckFail {
            get {
                return ResourceManager.GetString("TextupdateCheckFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for update.
        /// </summary>
        public static string TextUpdateChecking {
            get {
                return ResourceManager.GetString("TextUpdateChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software is up-to-date!.
        /// </summary>
        public static string TextUpdateUptodate {
            get {
                return ResourceManager.GetString("TextUpdateUptodate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TextVideo {
            get {
                return ResourceManager.GetString("TextVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter optional commandline arguments.
        /// </summary>
        public static string TextWallpaperCommandlineArgs {
            get {
                return ResourceManager.GetString("TextWallpaperCommandlineArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        public static string TextWallpaperFitFill {
            get {
                return ResourceManager.GetString("TextWallpaperFitFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TextWallpaperFitNone {
            get {
                return ResourceManager.GetString("TextWallpaperFitNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        public static string TextWallpaperFitUniform {
            get {
                return ResourceManager.GetString("TextWallpaperFitUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform Fill.
        /// </summary>
        public static string TextWallpaperFitUniformToFill {
            get {
                return ResourceManager.GetString("TextWallpaperFitUniformToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate same wallpaper.
        /// </summary>
        public static string TextWallpaperLayoutDuplicate {
            get {
                return ResourceManager.GetString("TextWallpaperLayoutDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected screen only.
        /// </summary>
        public static string TextWallpaperLayoutPerScreen {
            get {
                return ResourceManager.GetString("TextWallpaperLayoutPerScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span across screens.
        /// </summary>
        public static string TextWallpaperLayoutSpan {
            get {
                return ResourceManager.GetString("TextWallpaperLayoutSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TextWallpaperType {
            get {
                return ResourceManager.GetString("TextWallpaperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string TextWebsite {
            get {
                return ResourceManager.GetString("TextWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Stream.
        /// </summary>
        public static string TextWebStream {
            get {
                return ResourceManager.GetString("TextWebStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string TextWelcome {
            get {
                return ResourceManager.GetString("TextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string TextYes {
            get {
                return ResourceManager.GetString("TextYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Player.
        /// </summary>
        public static string TileVideoPlayer {
            get {
                return ResourceManager.GetString("TileVideoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set all supported file types as wallpaper..
        /// </summary>
        public static string TipAddWallpaperFileBrowse {
            get {
                return ResourceManager.GetString("TipAddWallpaperFileBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the web page of the URL you entered as wallpaper..
        /// </summary>
        public static string TipAddWallpaperURL {
            get {
                return ResourceManager.GetString("TipAddWallpaperURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set what to do when any application is in focus..
        /// </summary>
        public static string TipAppFocus {
            get {
                return ResourceManager.GetString("TipAppFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set what to do when fullscreen games/applications are running..
        /// </summary>
        public static string TipAppFullScreen {
            get {
                return ResourceManager.GetString("TipAppFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set different wallpaper playback rules based on running application..
        /// </summary>
        public static string TipAppRules {
            get {
                return ResourceManager.GetString("TipAppRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively adapts to system theme settings, to change appearance goto.
        /// </summary>
        public static string TipAppTheme {
            get {
                return ResourceManager.GetString("TipAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume level of all wallpapers..
        /// </summary>
        public static string TipAudioMaster {
            get {
                return ResourceManager.GetString("TipAudioMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change playback when AC power is disconnected..
        /// </summary>
        public static string TipBatteryPower {
            get {
                return ResourceManager.GetString("TipBatteryPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the port for debugging webpage wallpapers, browser restart is required for changes to take effect.
        ///When ready navigate to http://localhost:portnumber to access developer console..
        /// </summary>
        public static string TipBrowserDebuggingPort {
            get {
                return ResourceManager.GetString("TipBrowserDebuggingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show developer menu..
        /// </summary>
        public static string TipDebug {
            get {
                return ResourceManager.GetString("TipDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a picture of animated wallpaper as desktop wallpaper..
        /// </summary>
        public static string TipDesktopPicture {
            get {
                return ResourceManager.GetString("TipDesktopPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose whether to pause wallpaper on all screens or only the relevant screen in which application is focused/fullscreen..
        /// </summary>
        public static string TipDisplayPauseRule {
            get {
                return ResourceManager.GetString("TipDisplayPauseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create log report file..
        /// </summary>
        public static string TipExportLogs {
            get {
                return ResourceManager.GetString("TipExportLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the player used for gif wallpaper..
        /// </summary>
        public static string TipGifPlayer {
            get {
                return ResourceManager.GetString("TipGifPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System-tray icon visibility, lively will continue to run with the icon hidden..
        /// </summary>
        public static string TipHideSysTray {
            get {
                return ResourceManager.GetString("TipHideSysTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively will restart to apply the new language..
        /// </summary>
        public static string TipLanguage {
            get {
                return ResourceManager.GetString("TipLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish the setup to continue..
        /// </summary>
        public static string TipLivelySetupOnClose {
            get {
                return ResourceManager.GetString("TipLivelySetupOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set a picture of animated wallpaper as lockscreen wallpaper..
        /// </summary>
        public static string TipLockscreenPicture {
            get {
                return ResourceManager.GetString("TipLockscreenPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper pause algorithm..
        /// </summary>
        public static string TipPauseAlgorithm {
            get {
                return ResourceManager.GetString("TipPauseAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change playback when Windows Power Saving Mode is enabled..
        /// </summary>
        public static string TipPowerSavingModePower {
            get {
                return ResourceManager.GetString("TipPowerSavingModePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change playback when running a Remote Desktop session..
        /// </summary>
        public static string TipRemoteDesktopPower {
            get {
                return ResourceManager.GetString("TipRemoteDesktopPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the selected inactivity period use the current wallpaper as your screensaver..
        /// </summary>
        public static string TipScreensaver {
            get {
                return ResourceManager.GetString("TipScreensaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If supported video stream link is detected use the video player instead of loading the webpage..
        /// </summary>
        public static string TipStreamWallpaperDetect {
            get {
                return ResourceManager.GetString("TipStreamWallpaperDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the desired video quality for online streams..
        /// </summary>
        public static string TipStreamWallpaperVideoQuality {
            get {
                return ResourceManager.GetString("TipStreamWallpaperVideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change software release from beta to stable or vice versa..
        /// </summary>
        public static string TipSwitchSoftwareBranch {
            get {
                return ResourceManager.GetString("TipSwitchSoftwareBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change system taskbar appearance..
        /// </summary>
        public static string TipTaskbarTheme {
            get {
                return ResourceManager.GetString("TipTaskbarTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the wallpaper tiles in Library..
        /// </summary>
        public static string TipTileSize {
            get {
                return ResourceManager.GetString("TipTileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For low-end systems select Lite mode..
        /// </summary>
        public static string TipUIMode {
            get {
                return ResourceManager.GetString("TipUIMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use hardware acceleration when possible..
        /// </summary>
        public static string TipVideoHardwareDecode {
            get {
                return ResourceManager.GetString("TipVideoHardwareDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the player used for video wallpaper..
        /// </summary>
        public static string TipVideoPlayer {
            get {
                return ResourceManager.GetString("TipVideoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path used to store wallpaper files..
        /// </summary>
        public static string TipWallpaperDir {
            get {
                return ResourceManager.GetString("TipWallpaperDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper scaling algorithm..
        /// </summary>
        public static string TipWallpaperFit {
            get {
                return ResourceManager.GetString("TipWallpaperFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ways to interact with wallpaper..
        /// </summary>
        public static string TipWallpaperInput {
            get {
                return ResourceManager.GetString("TipWallpaperInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How wallpaper is applied to connected display devices..
        /// </summary>
        public static string TipWallpaperLayout {
            get {
                return ResourceManager.GetString("TipWallpaperLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause wallpaper playback when desktop is not focused..
        /// </summary>
        public static string TipWallpaperPlayback {
            get {
                return ResourceManager.GetString("TipWallpaperPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store temporary files on disk instead of memory, settings gets restored when browser is restarted..
        /// </summary>
        public static string TipWebBrowserDiskCache {
            get {
                return ResourceManager.GetString("TipWebBrowserDiskCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEF(Chromium Embedded Framework) is a lightweight chromium engine.
        ///Edge is the built in webview of windows 10..
        /// </summary>
        public static string TipWebBrowserEngine {
            get {
                return ResourceManager.GetString("TipWebBrowserEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively needs to run in the background for wallpaper playback..
        /// </summary>
        public static string TipWindowsStartup {
            get {
                return ResourceManager.GetString("TipWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wallpaper.
        /// </summary>
        public static string TitleAddWallpaper {
            get {
                return ResourceManager.GetString("TitleAddWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications Focused.
        /// </summary>
        public static string TitleAppFocus {
            get {
                return ResourceManager.GetString("TitleAppFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications Fullscreen.
        /// </summary>
        public static string TitleAppFullScreen {
            get {
                return ResourceManager.GetString("TitleAppFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively Wallpaper.
        /// </summary>
        public static string TitleAppName {
            get {
                return ResourceManager.GetString("TitleAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Rules.
        /// </summary>
        public static string TitleAppRules {
            get {
                return ResourceManager.GetString("TitleAppRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string TitleAppTheme {
            get {
                return ResourceManager.GetString("TitleAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string TitleAudio {
            get {
                return ResourceManager.GetString("TitleAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play audio only when desktop is focused.
        /// </summary>
        public static string TitleAudioDesktopOnly {
            get {
                return ResourceManager.GetString("TitleAudioDesktopOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Volume.
        /// </summary>
        public static string TitleAudioMaster {
            get {
                return ResourceManager.GetString("TitleAudioMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play audio on screen.
        /// </summary>
        public static string TitleAudioPlayOnScreen {
            get {
                return ResourceManager.GetString("TitleAudioPlayOnScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on Battery Power.
        /// </summary>
        public static string TitleBatteryPower {
            get {
                return ResourceManager.GetString("TitleBatteryPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse for video, gif, webpage... file to set as wallpaper.
        /// </summary>
        public static string TitleBrowseFile {
            get {
                return ResourceManager.GetString("TitleBrowseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Port.
        /// </summary>
        public static string TitleBrowserDebuggingPort {
            get {
                return ResourceManager.GetString("TitleBrowserDebuggingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string TitleChangelog {
            get {
                return ResourceManager.GetString("TitleChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string TitleCommunity {
            get {
                return ResourceManager.GetString("TitleCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string TitleDebug {
            get {
                return ResourceManager.GetString("TitleDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string TitleDeleteConfirmation {
            get {
                return ResourceManager.GetString("TitleDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Picture.
        /// </summary>
        public static string TitleDesktopPicture {
            get {
                return ResourceManager.GetString("TitleDesktopPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Pause Rule.
        /// </summary>
        public static string TitleDisplayPauseRule {
            get {
                return ResourceManager.GetString("TitleDisplayPauseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentation.
        /// </summary>
        public static string TitleDocumentation {
            get {
                return ResourceManager.GetString("TitleDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter URL.
        /// </summary>
        public static string TitleEnterUrl {
            get {
                return ResourceManager.GetString("TitleEnterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log File.
        /// </summary>
        public static string TitleExportLogs {
            get {
                return ResourceManager.GetString("TitleExportLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TitleGeneral {
            get {
                return ResourceManager.GetString("TitleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gif Player.
        /// </summary>
        public static string TitleGifPlayer {
            get {
                return ResourceManager.GetString("TitleGifPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string TitleHelp {
            get {
                return ResourceManager.GetString("TitleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System-tray Icon.
        /// </summary>
        public static string TitleHideSysTray {
            get {
                return ResourceManager.GetString("TitleHideSysTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string TitleInteraction {
            get {
                return ResourceManager.GetString("TitleInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string TitleLanguage {
            get {
                return ResourceManager.GetString("TitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string TitleLibrary {
            get {
                return ResourceManager.GetString("TitleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively Setup.
        /// </summary>
        public static string TitleLivelySetup {
            get {
                return ResourceManager.GetString("TitleLivelySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TitleLocation {
            get {
                return ResourceManager.GetString("TitleLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockscreen Picture.
        /// </summary>
        public static string TitleLockscreenPicture {
            get {
                return ResourceManager.GetString("TitleLockscreenPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string TitleMisc {
            get {
                return ResourceManager.GetString("TitleMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string TitleMute {
            get {
                return ResourceManager.GetString("TitleMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Algorithm.
        /// </summary>
        public static string TitlePauseAlgo {
            get {
                return ResourceManager.GetString("TitlePauseAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string TitlePerformance {
            get {
                return ResourceManager.GetString("TitlePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist.
        /// </summary>
        public static string TitlePlaylist {
            get {
                return ResourceManager.GetString("TitlePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string TitlePleaseWait {
            get {
                return ResourceManager.GetString("TitlePleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on Battery Saver.
        /// </summary>
        public static string TitlePowerSavingModePower {
            get {
                return ResourceManager.GetString("TitlePowerSavingModePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on Remote Desktop.
        /// </summary>
        public static string TitleRemoteDesktopPower {
            get {
                return ResourceManager.GetString("TitleRemoteDesktopPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Bug.
        /// </summary>
        public static string TitleReportBug {
            get {
                return ResourceManager.GetString("TitleReportBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling/Fit.
        /// </summary>
        public static string TitleScalingFit {
            get {
                return ResourceManager.GetString("TitleScalingFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string TitleScreenLayout {
            get {
                return ResourceManager.GetString("TitleScreenLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screensaver.
        /// </summary>
        public static string TitleScreensaver {
            get {
                return ResourceManager.GetString("TitleScreensaver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On resume, display logon screen.
        /// </summary>
        public static string TitleScreensaverLockOnResume {
            get {
                return ResourceManager.GetString("TitleScreensaverLockOnResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string TitleSelectFile {
            get {
                return ResourceManager.GetString("TitleSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Confirmation.
        /// </summary>
        public static string TitleSkipConfirm {
            get {
                return ResourceManager.GetString("TitleSkipConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code.
        /// </summary>
        public static string TitleSourceCode {
            get {
                return ResourceManager.GetString("TitleSourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string TitleStore {
            get {
                return ResourceManager.GetString("TitleStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        public static string TitleStreamWallpaper {
            get {
                return ResourceManager.GetString("TitleStreamWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Streams.
        /// </summary>
        public static string TitleStreamWallpaperDetect {
            get {
                return ResourceManager.GetString("TitleStreamWallpaperDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Quality.
        /// </summary>
        public static string TitleStreamWallpaperVideoQuality {
            get {
                return ResourceManager.GetString("TitleStreamWallpaperVideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string TitleSystem {
            get {
                return ResourceManager.GetString("TitleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taskbar Theme.
        /// </summary>
        public static string TitleTaskbarTheme {
            get {
                return ResourceManager.GetString("TitleTaskbarTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size.
        /// </summary>
        public static string TitleTileSize {
            get {
                return ResourceManager.GetString("TitleTileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        public static string TitleUIMode {
            get {
                return ResourceManager.GetString("TitleUIMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string TitleUpdates {
            get {
                return ResourceManager.GetString("TitleUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TitleVideo {
            get {
                return ResourceManager.GetString("TitleVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Decode.
        /// </summary>
        public static string TitleVideoHardwareDecode {
            get {
                return ResourceManager.GetString("TitleVideoHardwareDecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string TitleWallpaper {
            get {
                return ResourceManager.GetString("TitleWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Directory.
        /// </summary>
        public static string TitleWallpaperDir {
            get {
                return ResourceManager.GetString("TitleWallpaperDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move existing wallpapers to new folder.
        /// </summary>
        public static string TitleWallpaperDirMoveExisting {
            get {
                return ResourceManager.GetString("TitleWallpaperDirMoveExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a fit.
        /// </summary>
        public static string TitleWallpaperFit {
            get {
                return ResourceManager.GetString("TitleWallpaperFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Input.
        /// </summary>
        public static string TitleWallpaperInput {
            get {
                return ResourceManager.GetString("TitleWallpaperInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placement Method.
        /// </summary>
        public static string TitleWallpaperLayout {
            get {
                return ResourceManager.GetString("TitleWallpaperLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Playback.
        /// </summary>
        public static string TitleWallpaperPlayback {
            get {
                return ResourceManager.GetString("TitleWallpaperPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string TitleWarning {
            get {
                return ResourceManager.GetString("TitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string TitleWebBrowser {
            get {
                return ResourceManager.GetString("TitleWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk cache.
        /// </summary>
        public static string TitleWebBrowserDiskCache {
            get {
                return ResourceManager.GetString("TitleWebBrowserDiskCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string TitleWebBrowserEngine {
            get {
                return ResourceManager.GetString("TitleWebBrowserEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Webpage.
        /// </summary>
        public static string TitleWebpageLoad {
            get {
                return ResourceManager.GetString("TitleWebpageLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string TitleWindowsStartup {
            get {
                return ResourceManager.GetString("TitleWindowsStartup", resourceCulture);
            }
        }
    }
}
