//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace livelywpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("livelywpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper playback behaviour based on running application..
        /// </summary>
        public static string DescriptionAppRules {
            get {
                return ResourceManager.GetString("DescriptionAppRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively is minimized to systemtray, right click lively icon to continue..
        /// </summary>
        public static string DescriptionMinimizedTray {
            get {
                return ResourceManager.GetString("DescriptionMinimizedTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to begin recording..
        /// </summary>
        public static string DescriptionRecordStart {
            get {
                return ResourceManager.GetString("DescriptionRecordStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This wizard will get you started on setting up Lively..
        /// </summary>
        public static string DescriptionWelcomeWizard {
            get {
                return ResourceManager.GetString("DescriptionWelcomeWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string HeaderAppRules {
            get {
                return ResourceManager.GetString("HeaderAppRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string TextAdd {
            get {
                return ResourceManager.GetString("TextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string TextApplication {
            get {
                return ResourceManager.GetString("TextApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string TextAuthor {
            get {
                return ResourceManager.GetString("TextAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TextBack {
            get {
                return ResourceManager.GetString("TextBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed!.
        /// </summary>
        public static string TextCompleted {
            get {
                return ResourceManager.GetString("TextCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Video.
        /// </summary>
        public static string TextConvertVideo {
            get {
                return ResourceManager.GetString("TextConvertVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customise Wallpaper.
        /// </summary>
        public static string TextCustomiseWallpaper {
            get {
                return ResourceManager.GetString("TextCustomiseWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Wallpaper.
        /// </summary>
        public static string TextDeleteWallpaper {
            get {
                return ResourceManager.GetString("TextDeleteWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export lively .zip.
        /// </summary>
        public static string TextExportWallpaperZip {
            get {
                return ResourceManager.GetString("TextExportWallpaperZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string TextmoreInfo {
            get {
                return ResourceManager.GetString("TextmoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse interaction when Application Focused.
        /// </summary>
        public static string TextMouseInteractOnDesktop {
            get {
                return ResourceManager.GetString("TextMouseInteractOnDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string TextNext {
            get {
                return ResourceManager.GetString("TextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        public static string TextPerformanceKill {
            get {
                return ResourceManager.GetString("TextPerformanceKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string TextPerformanceNone {
            get {
                return ResourceManager.GetString("TextPerformanceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string TextPerformanePause {
            get {
                return ResourceManager.GetString("TextPerformanePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string TextRemove {
            get {
                return ResourceManager.GetString("TextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string TextRule {
            get {
                return ResourceManager.GetString("TextRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string TextSearch {
            get {
                return ResourceManager.GetString("TextSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Wallpaper.
        /// </summary>
        public static string TextSetWallpaper {
            get {
                return ResourceManager.GetString("TextSetWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Disk.
        /// </summary>
        public static string TextShowOnDisk {
            get {
                return ResourceManager.GetString("TextShowOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string TextSource {
            get {
                return ResourceManager.GetString("TextSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string TextStop {
            get {
                return ResourceManager.GetString("TextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string TextTileSizeLarge {
            get {
                return ResourceManager.GetString("TextTileSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TextTileSizeNormal {
            get {
                return ResourceManager.GetString("TextTileSizeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string TextTileSizeSmall {
            get {
                return ResourceManager.GetString("TextTileSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headless.
        /// </summary>
        public static string TextUIHeadless {
            get {
                return ResourceManager.GetString("TextUIHeadless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite.
        /// </summary>
        public static string TextUILite {
            get {
                return ResourceManager.GetString("TextUILite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string TextUINormal {
            get {
                return ResourceManager.GetString("TextUINormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TextWallpaperType {
            get {
                return ResourceManager.GetString("TextWallpaperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string TextWelcome {
            get {
                return ResourceManager.GetString("TextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Player.
        /// </summary>
        public static string TileVideoPlayer {
            get {
                return ResourceManager.GetString("TileVideoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set what to do when any application is in focus..
        /// </summary>
        public static string TipAppFocus {
            get {
                return ResourceManager.GetString("TipAppFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set what to do when fullscreen games/applications are running..
        /// </summary>
        public static string TipAppFullScreen {
            get {
                return ResourceManager.GetString("TipAppFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set different wallpaper playback rules based on running application..
        /// </summary>
        public static string TipAppRules {
            get {
                return ResourceManager.GetString("TipAppRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively adapts to system theme settings, to change appearance goto.
        /// </summary>
        public static string TipAppTheme {
            get {
                return ResourceManager.GetString("TipAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (For battery operated systems only) Change playback when AC power is disconnected..
        /// </summary>
        public static string TipBatteryPower {
            get {
                return ResourceManager.GetString("TipBatteryPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the port for debugging webpage wallpapers, browser restart is required for changes to take effect.
        ///When ready navigate to http://localhost:portnumber to access developer console..
        /// </summary>
        public static string TipBrowserDebuggingPort {
            get {
                return ResourceManager.GetString("TipBrowserDebuggingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per: Pause wallpaper only on the screen in which application is focused/fullscreen.
        ///All: Pause wallpaper on all screen(s) if any application is focused/fullscreen..
        /// </summary>
        public static string TipDisplayPauseRule {
            get {
                return ResourceManager.GetString("TipDisplayPauseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively will restart to apply the new language..
        /// </summary>
        public static string TipLanguage {
            get {
                return ResourceManager.GetString("TipLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish the setup to continue..
        /// </summary>
        public static string TipLivelySetupOnClose {
            get {
                return ResourceManager.GetString("TipLivelySetupOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground: Lightweight, only checks the single process that is in foreground to determine wallpaper playback behaviour.
        ///All Process: Heavier, Scans all the process to determine playback behaviour..
        /// </summary>
        public static string TipPauseAlgorithm {
            get {
                return ResourceManager.GetString("TipPauseAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If supported video stream link is detected use the video player instead of loading the webpage..
        /// </summary>
        public static string TipStreamWallpaperDetect {
            get {
                return ResourceManager.GetString("TipStreamWallpaperDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the desired video quality for online streams..
        /// </summary>
        public static string TipStreamWallpaperVideoQuality {
            get {
                return ResourceManager.GetString("TipStreamWallpaperVideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the wallpaper tiles in Library..
        /// </summary>
        public static string TipTileSize {
            get {
                return ResourceManager.GetString("TipTileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For low-end systems select Lite mode..
        /// </summary>
        public static string TipUIMode {
            get {
                return ResourceManager.GetString("TipUIMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the player used for video wallpaper.
        ///libVLC is recommended..
        /// </summary>
        public static string TipVideoPlayer {
            get {
                return ResourceManager.GetString("TipVideoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path used to store wallpaper files..
        /// </summary>
        public static string TipWallpaperDir {
            get {
                return ResourceManager.GetString("TipWallpaperDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ways to interact with wallpaper..
        /// </summary>
        public static string TipWallpaperInput {
            get {
                return ResourceManager.GetString("TipWallpaperInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause wallpaper playback when desktop is not focused..
        /// </summary>
        public static string TipWallpaperPlayback {
            get {
                return ResourceManager.GetString("TipWallpaperPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEF(Chromium Embedded Framework) is a lightweight chromium engine.
        ///Edge is the built in webview of windows 10..
        /// </summary>
        public static string TipWebBrowserEngine {
            get {
                return ResourceManager.GetString("TipWebBrowserEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively needs to run in the background for wallpaper playback..
        /// </summary>
        public static string TipWindowsStartup {
            get {
                return ResourceManager.GetString("TipWindowsStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TitleAbout {
            get {
                return ResourceManager.GetString("TitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Wallpaper.
        /// </summary>
        public static string TitleAddWallpaper {
            get {
                return ResourceManager.GetString("TitleAddWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications Focused.
        /// </summary>
        public static string TitleAppFocus {
            get {
                return ResourceManager.GetString("TitleAppFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications Fullscreen.
        /// </summary>
        public static string TitleAppFullScreen {
            get {
                return ResourceManager.GetString("TitleAppFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively Wallpaper.
        /// </summary>
        public static string TitleAppName {
            get {
                return ResourceManager.GetString("TitleAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Rules.
        /// </summary>
        public static string TitleAppRules {
            get {
                return ResourceManager.GetString("TitleAppRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string TitleAppTheme {
            get {
                return ResourceManager.GetString("TitleAppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string TitleAudio {
            get {
                return ResourceManager.GetString("TitleAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on Battery Power.
        /// </summary>
        public static string TitleBatteryPower {
            get {
                return ResourceManager.GetString("TitleBatteryPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging Port.
        /// </summary>
        public static string TitleBrowserDebuggingPort {
            get {
                return ResourceManager.GetString("TitleBrowserDebuggingPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Pause Rule.
        /// </summary>
        public static string TitleDisplayPauseRule {
            get {
                return ResourceManager.GetString("TitleDisplayPauseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string TitleGeneral {
            get {
                return ResourceManager.GetString("TitleGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string TitleInteraction {
            get {
                return ResourceManager.GetString("TitleInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string TitleLanguage {
            get {
                return ResourceManager.GetString("TitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string TitleLibrary {
            get {
                return ResourceManager.GetString("TitleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively Setup.
        /// </summary>
        public static string TitleLivelySetup {
            get {
                return ResourceManager.GetString("TitleLivelySetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string TitleMisc {
            get {
                return ResourceManager.GetString("TitleMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Algorithm.
        /// </summary>
        public static string TitlePauseAlgo {
            get {
                return ResourceManager.GetString("TitlePauseAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string TitlePerformance {
            get {
                return ResourceManager.GetString("TitlePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        public static string TitleStreamWallpaper {
            get {
                return ResourceManager.GetString("TitleStreamWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Streams.
        /// </summary>
        public static string TitleStreamWallpaperDetect {
            get {
                return ResourceManager.GetString("TitleStreamWallpaperDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Quality.
        /// </summary>
        public static string TitleStreamWallpaperVideoQuality {
            get {
                return ResourceManager.GetString("TitleStreamWallpaperVideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Size.
        /// </summary>
        public static string TitleTileSize {
            get {
                return ResourceManager.GetString("TitleTileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        public static string TitleUIMode {
            get {
                return ResourceManager.GetString("TitleUIMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string TitleVideo {
            get {
                return ResourceManager.GetString("TitleVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper.
        /// </summary>
        public static string TitleWallpaper {
            get {
                return ResourceManager.GetString("TitleWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Directory.
        /// </summary>
        public static string TitleWallpaperDir {
            get {
                return ResourceManager.GetString("TitleWallpaperDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Input.
        /// </summary>
        public static string TitleWallpaperInput {
            get {
                return ResourceManager.GetString("TitleWallpaperInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Playback.
        /// </summary>
        public static string TitleWallpaperPlayback {
            get {
                return ResourceManager.GetString("TitleWallpaperPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string TitleWebBrowser {
            get {
                return ResourceManager.GetString("TitleWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string TitleWebBrowserEngine {
            get {
                return ResourceManager.GetString("TitleWebBrowserEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string TitleWindowsStartup {
            get {
                return ResourceManager.GetString("TitleWindowsStartup", resourceCulture);
            }
        }
    }
}
