//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace livelywpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("livelywpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Display(s).
        /// </summary>
        public static string cmbBoxAllDisplays {
            get {
                return ResourceManager.GetString("cmbBoxAllDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XamlAnimatedGif.
        /// </summary>
        public static string cmbBoxGIFPlayer1 {
            get {
                return ResourceManager.GetString("cmbBoxGIFPlayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low memory usage, high cpu usage.
        /// </summary>
        public static string cmbBoxGIFPlayer1ToolTip {
            get {
                return ResourceManager.GetString("cmbBoxGIFPlayer1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectShow.
        /// </summary>
        public static string cmbBoxGIFPlayer2 {
            get {
                return ResourceManager.GetString("cmbBoxGIFPlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower cpu usage (depending on codec settings).
        /// </summary>
        public static string cmbBoxGIFPlayer2ToolTip {
            get {
                return ResourceManager.GetString("cmbBoxGIFPlayer2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill(Free Memory).
        /// </summary>
        public static string cmbBoxKill {
            get {
                return ResourceManager.GetString("cmbBoxKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string cmbBoxNothing {
            get {
                return ResourceManager.GetString("cmbBoxNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Processes (Experimental).
        /// </summary>
        public static string cmbBoxPaugeAlgorithmAllProcess {
            get {
                return ResourceManager.GetString("cmbBoxPaugeAlgorithmAllProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string cmbBoxPause {
            get {
                return ResourceManager.GetString("cmbBoxPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Process.
        /// </summary>
        public static string cmbBoxPauseAlgorithmForeground {
            get {
                return ResourceManager.GetString("cmbBoxPauseAlgorithmForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Display.
        /// </summary>
        public static string cmbBoxPerDisplay {
            get {
                return ResourceManager.GetString("cmbBoxPerDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        public static string cmbBoxSpan {
            get {
                return ResourceManager.GetString("cmbBoxSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Foundation.
        /// </summary>
        public static string cmbBoxVideoPlayer1 {
            get {
                return ResourceManager.GetString("cmbBoxVideoPlayer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectShow(Lav, ffdshow..).
        /// </summary>
        public static string cmbBoxVideoPlayer2 {
            get {
                return ResourceManager.GetString("cmbBoxVideoPlayer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f37\fbidi  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter commandline arguments for the application if any (optional, leave blank if none):-.
        /// </summary>
        public static string msgAppCommandLineArgs {
            get {
                return ResourceManager.GetString("msgAppCommandLineArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Arguments.
        /// </summary>
        public static string msgAppCommandLineArgsTitle {
            get {
                return ResourceManager.GetString("msgAppCommandLineArgsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected wallpaper(application) has no graphical user interface(GUI).
        ///Terminating application....
        /// </summary>
        public static string msgAppGUIFailure {
            get {
                return ResourceManager.GetString("msgAppGUIFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to catch application window.
        ///The wallpaper(application) is taking too long to start(more than ~30sec), it could be due to:
        ///Virus scan/ Application is too big.
        ///Wait &amp; try again. (optionally you can edit the waiting time, check out wiki for more information.)
        ///Terminating application....
        /// </summary>
        public static string msgAppTimeout {
            get {
                return ResourceManager.GetString("msgAppTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damaged wallpaper file, try redownloading..
        /// </summary>
        public static string msgDamangedLivelyFile {
            get {
                return ResourceManager.GetString("msgDamangedLivelyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to permanently delete the wallpaper from the disk?.
        /// </summary>
        public static string msgDeleteConfirmation {
            get {
                return ResourceManager.GetString("msgDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Deletion.
        /// </summary>
        public static string msgDeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("msgDeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently running as wallpaper, cannot delete!
        ///Close this wallpaper to delete it..
        /// </summary>
        public static string msgDeletionFailure {
            get {
                return ResourceManager.GetString("msgDeletionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion Failed.
        /// </summary>
        public static string msgDeletionFailureTitle {
            get {
                return ResourceManager.GetString("msgDeletionFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file format is not supported for drag &amp; drop, open it in &apos;Type&apos; page instead..
        /// </summary>
        public static string msgDragDropOtherFormats {
            get {
                return ResourceManager.GetString("msgDragDropOtherFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively: Not Supported.
        /// </summary>
        public static string msgDragDropOtherFormatsTitle {
            get {
                return ResourceManager.GetString("msgDragDropOtherFormatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are opening an external application as wallpaper.
        ///Malicious applications can host malware, virus.. and do harm to your system.
        ///Only continue if this application comes from a trusted source..
        /// </summary>
        public static string msgExternalAppWarning {
            get {
                return ResourceManager.GetString("msgExternalAppWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string msgExternalAppWarningTitle {
            get {
                return ResourceManager.GetString("msgExternalAppWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF file playback failed.
        ///Is the GIF file corrupted? Try redownloading..
        /// </summary>
        public static string msgGIFfailure {
            get {
                return ResourceManager.GetString("msgGIFfailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively cannot work properly with Windows High Contrast mode enabled!
        ///Disable High Contrast mode &amp; Try again..
        /// </summary>
        public static string msgHighContrastFailure {
            get {
                return ResourceManager.GetString("msgHighContrastFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to open an external webpage on your browser.
        ///
        ///URL:-.
        /// </summary>
        public static string msgLoadExternalLink {
            get {
                return ResourceManager.GetString("msgLoadExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Webpage?.
        /// </summary>
        public static string msgLoadExternalLinkTitle {
            get {
                return ResourceManager.GetString("msgLoadExternalLinkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting up external application...
        /// </summary>
        public static string msgLoadingAppWallpaper {
            get {
                return ResourceManager.GetString("msgLoadingAppWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media playback failed: Missing Codec/ Corrupted File.
        ///Install LAV codec &amp; Try switching to Directshow videoplayer.
        ///.
        /// </summary>
        public static string msgMediaFoundationFailure {
            get {
                return ResourceManager.GetString("msgMediaFoundationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media playback failed: Missing Codec/ Corrupted File.
        ///Don&apos;t forget to install LAV codec.
        ///.
        /// </summary>
        public static string msgMediakitFailure {
            get {
                return ResourceManager.GetString("msgMediakitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently restoring previous wallpaper(s), please wait..
        /// </summary>
        public static string msgRestoringInProgress {
            get {
                return ResourceManager.GetString("msgRestoringInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring previous wallpaper(s)...
        /// </summary>
        public static string msgRestoringPrevWallpapers {
            get {
                return ResourceManager.GetString("msgRestoringPrevWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively was not closed properly, starting in safe mode.
        ///Do you wish to restore previously running wallpapers?
        ///Error information is saved at:-
        ///.
        /// </summary>
        public static string msgSafeModeWarning {
            get {
                return ResourceManager.GetString("msgSafeModeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively is already running!
        ///If not-responding terminate process &quot;livelywpf&quot; in taskmanager &amp; try again..
        /// </summary>
        public static string msgSingleInstanceOnly {
            get {
                return ResourceManager.GetString("msgSingleInstanceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter website link to load, Shadertoy.com shader links are supported:-.
        /// </summary>
        public static string msgUrlLoad {
            get {
                return ResourceManager.GetString("msgUrlLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load webpage.
        /// </summary>
        public static string msgUrlLoadTitle {
            get {
                return ResourceManager.GetString("msgUrlLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to load an external website.
        ///Malicious Web pages can be harmful to your computer (malware, virus ..)
        ///Only enter links to websites that you trust..
        /// </summary>
        public static string msgUrlWarning {
            get {
                return ResourceManager.GetString("msgUrlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string msgUrlWarningTitle {
            get {
                return ResourceManager.GetString("msgUrlWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web browser component is missing, either download separately:-
        ///https://github.com/rocksdanister/lively-cef 
        ///OR
        ///Download the full version of lively..
        /// </summary>
        public static string msgWebBrowserMissing {
            get {
                return ResourceManager.GetString("msgWebBrowserMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like some settings needs to be set to make Lively work:-  
        ///1. Open This PC(My Computer)
        ///2. Right-click empty area
        ///3. Select Properties
        ///4. Select Advanced System Settings
        ///5. Under Performance tab select Settings
        ///6. Enable Animate controls and elements inside windows &amp; Apply.
        ///
        ///If Windows 7 just set - Adjust for best appearance &amp; Apply.
        ///If still not working, close &amp; start Lively again/ restart windows.
        ///(Does not work in insider windows 10 builds).
        /// </summary>
        public static string msgWorkerWFailure {
            get {
                return ResourceManager.GetString("msgWorkerWFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string titleAbout {
            get {
                return ResourceManager.GetString("titleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string titleLibrary {
            get {
                return ResourceManager.GetString("titleLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string titleSettings {
            get {
                return ResourceManager.GetString("titleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string titleType {
            get {
                return ResourceManager.GetString("titleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m minimized to systemtray, right click lively icon for more options..
        /// </summary>
        public static string toolTipMinimizeMsg {
            get {
                return ResourceManager.GetString("toolTipMinimizeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available!.
        /// </summary>
        public static string toolTipUpdateMsg {
            get {
                return ResourceManager.GetString("toolTipUpdateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some wallpaper(s) were skipped because of missing file(s)!.
        /// </summary>
        public static string toolTipWallpaperSkip {
            get {
                return ResourceManager.GetString("toolTipWallpaperSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Rules.
        /// </summary>
        public static string txtApplicationRules {
            get {
                return ResourceManager.GetString("txtApplicationRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio In:.
        /// </summary>
        public static string txtAudioIn {
            get {
                return ResourceManager.GetString("txtAudioIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks browsers access to system audio..
        /// </summary>
        public static string txtAudioInToolTip {
            get {
                return ResourceManager.GetString("txtAudioInToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio is always disabled in multiple monitor systems..
        /// </summary>
        public static string txtAudioLabel1 {
            get {
                return ResourceManager.GetString("txtAudioLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Audio In&quot; is disabled, Web audio visualisers will not work..
        /// </summary>
        public static string txtAudioLabel2 {
            get {
                return ResourceManager.GetString("txtAudioLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Out:.
        /// </summary>
        public static string txtAudioOut {
            get {
                return ResourceManager.GetString("txtAudioOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute/mute video player..
        /// </summary>
        public static string txtAudioOutToolTip {
            get {
                return ResourceManager.GetString("txtAudioOutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser:.
        /// </summary>
        public static string txtBrowser {
            get {
                return ResourceManager.GetString("txtBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select web browser for web wallpapers(coming soon).
        /// </summary>
        public static string txtBrowserToolTip {
            get {
                return ResourceManager.GetString("txtBrowserToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Wallpapers.
        /// </summary>
        public static string txtCloseAllWallpapers {
            get {
                return ResourceManager.GetString("txtCloseAllWallpapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string txtComingSoon {
            get {
                return ResourceManager.GetString("txtComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Wallpapers.
        /// </summary>
        public static string txtContextMenuCloseAll {
            get {
                return ResourceManager.GetString("txtContextMenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Wallpaper.
        /// </summary>
        public static string txtContextMenuCloseWallpaper {
            get {
                return ResourceManager.GetString("txtContextMenuCloseWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Wallpaper.
        /// </summary>
        public static string txtContextMenuDeleteWallpaper {
            get {
                return ResourceManager.GetString("txtContextMenuDeleteWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string txtContextMenuExit {
            get {
                return ResourceManager.GetString("txtContextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export lively .zip.
        /// </summary>
        public static string txtContextMenuExport {
            get {
                return ResourceManager.GetString("txtContextMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Lively.
        /// </summary>
        public static string txtContextMenuOpenLively {
            get {
                return ResourceManager.GetString("txtContextMenuOpenLively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on Disk.
        /// </summary>
        public static string txtContextMenuShowOnDisk {
            get {
                return ResourceManager.GetString("txtContextMenuShowOnDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for update.
        /// </summary>
        public static string txtContextMenuUpdate1 {
            get {
                return ResourceManager.GetString("txtContextMenuUpdate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available!.
        /// </summary>
        public static string txtContextMenuUpdate2 {
            get {
                return ResourceManager.GetString("txtContextMenuUpdate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this Beta software?.
        /// </summary>
        public static string txtContextMenuUpdate3 {
            get {
                return ResourceManager.GetString("txtContextMenuUpdate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively is up-to-date!.
        /// </summary>
        public static string txtContextMenuUpdate4 {
            get {
                return ResourceManager.GetString("txtContextMenuUpdate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Checking for Update.
        /// </summary>
        public static string txtContextMenuUpdate5 {
            get {
                return ResourceManager.GetString("txtContextMenuUpdate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Wallpaper.
        /// </summary>
        public static string txtCreateWallpaper {
            get {
                return ResourceManager.GetString("txtCreateWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Lively zip file.
        /// </summary>
        public static string txtCreatingZip {
            get {
                return ResourceManager.GetString("txtCreatingZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Pause Rule:.
        /// </summary>
        public static string txtDisplayPauseRule {
            get {
                return ResourceManager.GetString("txtDisplayPauseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string txtDownload {
            get {
                return ResourceManager.GetString("txtDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Player:.
        /// </summary>
        public static string txtGIFPlayer {
            get {
                return ResourceManager.GetString("txtGIFPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directshow requires additionals plugins to be installed..
        /// </summary>
        public static string txtGifPlayerToolTip {
            get {
                return ResourceManager.GetString("txtGifPlayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Scaling/Fit:.
        /// </summary>
        public static string txtGifScaling {
            get {
                return ResourceManager.GetString("txtGifScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string txtHelp {
            get {
                return ResourceManager.GetString("txtHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string txtIgnore {
            get {
                return ResourceManager.GetString("txtIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string txtInstall {
            get {
                return ResourceManager.GetString("txtInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Wallpaper.
        /// </summary>
        public static string txtInstallWallpaper {
            get {
                return ResourceManager.GetString("txtInstallWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select wallpaper type to load:-.
        /// </summary>
        public static string txtLabel1 {
            get {
                return ResourceManager.GetString("txtLabel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribution:.
        /// </summary>
        public static string txtLabel10 {
            get {
                return ResourceManager.GetString("txtLabel10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should I use?.
        /// </summary>
        public static string txtLabel11 {
            get {
                return ResourceManager.GetString("txtLabel11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string txtLabel12 {
            get {
                return ResourceManager.GetString("txtLabel12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force 120FPS UI.
        /// </summary>
        public static string txtLabel120FPS {
            get {
                return ResourceManager.GetString("txtLabel120FPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string txtLabel13 {
            get {
                return ResourceManager.GetString("txtLabel13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact:.
        /// </summary>
        public static string txtLabel14 {
            get {
                return ResourceManager.GetString("txtLabel14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string txtLabel15 {
            get {
                return ResourceManager.GetString("txtLabel15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require app restart.
        /// </summary>
        public static string txtLabel16 {
            get {
                return ResourceManager.GetString("txtLabel16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string txtLabel17 {
            get {
                return ResourceManager.GetString("txtLabel17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gif.
        /// </summary>
        public static string txtLabel18 {
            get {
                return ResourceManager.GetString("txtLabel18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Browser.
        /// </summary>
        public static string txtLabel19 {
            get {
                return ResourceManager.GetString("txtLabel19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just drag and drop files if you prefer it that way instead..
        /// </summary>
        public static string txtLabel2 {
            get {
                return ResourceManager.GetString("txtLabel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string txtLabel20 {
            get {
                return ResourceManager.GetString("txtLabel20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set wallpaper(s) playback behaviour based on running application:-.
        /// </summary>
        public static string txtLabel21 {
            get {
                return ResourceManager.GetString("txtLabel21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string txtLabel22 {
            get {
                return ResourceManager.GetString("txtLabel22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string txtLabel23 {
            get {
                return ResourceManager.GetString("txtLabel23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Wallpaper Layout:-.
        /// </summary>
        public static string txtLabel24 {
            get {
                return ResourceManager.GetString("txtLabel24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a wallpaper type to create:-.
        /// </summary>
        public static string txtLabel25 {
            get {
                return ResourceManager.GetString("txtLabel25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library File: Create easy to share .zip file that loads wallpaper into Lively&apos;s library.
        ///To simply play a file as wallpaper, this is not required; just drag and drop the file to lively window..
        /// </summary>
        public static string txtLabel26 {
            get {
                return ResourceManager.GetString("txtLabel26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Website(optional):-.
        /// </summary>
        public static string txtLabel27 {
            get {
                return ResourceManager.GetString("txtLabel27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License(optional):-.
        /// </summary>
        public static string txtLabel28 {
            get {
                return ResourceManager.GetString("txtLabel28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:-.
        /// </summary>
        public static string txtLabel29 {
            get {
                return ResourceManager.GetString("txtLabel29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These materials are not sponsored by or affiliated with Unity Technologies, Godot, Bizhawk, Shadertoy.com.
        /// </summary>
        public static string txtLabel3 {
            get {
                return ResourceManager.GetString("txtLabel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:-.
        /// </summary>
        public static string txtLabel30 {
            get {
                return ResourceManager.GetString("txtLabel30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string txtLabel31 {
            get {
                return ResourceManager.GetString("txtLabel31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnail (200x200).
        /// </summary>
        public static string txtLabel32 {
            get {
                return ResourceManager.GetString("txtLabel32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string txtLabel33 {
            get {
                return ResourceManager.GetString("txtLabel33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Gif.
        /// </summary>
        public static string txtLabel34 {
            get {
                return ResourceManager.GetString("txtLabel34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Type:-.
        /// </summary>
        public static string txtLabel35 {
            get {
                return ResourceManager.GetString("txtLabel35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files and Folders being added:-.
        /// </summary>
        public static string txtLabel36 {
            get {
                return ResourceManager.GetString("txtLabel36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string txtLabel37 {
            get {
                return ResourceManager.GetString("txtLabel37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string txtLabel38 {
            get {
                return ResourceManager.GetString("txtLabel38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing Wallpaper.
        /// </summary>
        public static string txtLabel39 {
            get {
                return ResourceManager.GetString("txtLabel39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string txtLabel4 {
            get {
                return ResourceManager.GetString("txtLabel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string txtLabel5 {
            get {
                return ResourceManager.GetString("txtLabel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retro.
        /// </summary>
        public static string txtLabel6 {
            get {
                return ResourceManager.GetString("txtLabel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string txtLabel7 {
            get {
                return ResourceManager.GetString("txtLabel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string txtLabel8 {
            get {
                return ResourceManager.GetString("txtLabel8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Visualiser.
        /// </summary>
        public static string txtLabel9 {
            get {
                return ResourceManager.GetString("txtLabel9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string txtLabelApplication {
            get {
                return ResourceManager.GetString("txtLabelApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively.
        /// </summary>
        public static string txtLabelAppName {
            get {
                return ResourceManager.GetString("txtLabelAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction.
        /// </summary>
        public static string txtLabelInteraction {
            get {
                return ResourceManager.GetString("txtLabelInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string txtLabelRule {
            get {
                return ResourceManager.GetString("txtLabelRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Hardware Acceleration.
        /// </summary>
        public static string txtLabelSoftwareUIRendering {
            get {
                return ResourceManager.GetString("txtLabelSoftwareUIRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        public static string txtLabelStream {
            get {
                return ResourceManager.GetString("txtLabelStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Quality.
        /// </summary>
        public static string txtLabelVideoQuality {
            get {
                return ResourceManager.GetString("txtLabelVideoQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is currently in development.
        ///Do NOT run programs such as CHROME, STEAM.. which spawn multiple Subprocesses.
        ///THERE WILL BE BUGS &amp; CRASHES, PROCEED WITH CAUTION!!!.
        /// </summary>
        public static string txtLivelyAppWarning {
            get {
                return ResourceManager.GetString("txtLivelyAppWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string txtLivelyErrorMsgTitle {
            get {
                return ResourceManager.GetString("txtLivelyErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string txtLivelyWaitMsgTitle {
            get {
                return ResourceManager.GetString("txtLivelyWaitMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string txtLivelyWallpaperTypeApp {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated GIF.
        /// </summary>
        public static string txtLivelyWallpaperTypeGIF {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godot Application.
        /// </summary>
        public static string txtLivelyWallpaperTypeGodot {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeGodot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Application.
        /// </summary>
        public static string txtLivelyWallpaperTypeUnity {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Audio Reactive.
        /// </summary>
        public static string txtLivelyWallpaperTypeUnityAudio {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeUnityAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string txtLivelyWallpaperTypeUrl {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string txtLivelyWallpaperTypeVideo {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string txtLivelyWallpaperTypeWeb {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Audio Reactive.
        /// </summary>
        public static string txtLivelyWallpaperTypeWebAudio {
            get {
                return ResourceManager.GetString("txtLivelyWallpaperTypeWebAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated Tile:.
        /// </summary>
        public static string txtLiveTile {
            get {
                return ResourceManager.GetString("txtLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Experimental) Wallpaper preview on tile..
        /// </summary>
        public static string txtLiveTileToolTip {
            get {
                return ResourceManager.GetString("txtLiveTileToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Wallpapers....
        /// </summary>
        public static string txtMoreWp {
            get {
                return ResourceManager.GetString("txtMoreWp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string txtMouse {
            get {
                return ResourceManager.GetString("txtMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fille all the required text fields..
        /// </summary>
        public static string txtMsgFillAllFields {
            get {
                return ResourceManager.GetString("txtMsgFillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper file not selected.
        /// </summary>
        public static string txtMsgSelectWallpaperFile {
            get {
                return ResourceManager.GetString("txtMsgSelectWallpaperFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updater is not supported in portable version of Lively, download latest portable release from the website..
        /// </summary>
        public static string txtMsgUpdaterPortableUnsupported {
            get {
                return ResourceManager.GetString("txtMsgUpdaterPortableUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:
        ///(1) Lively window ignores these rules.
        ///(2) Audio is always muted when other apps are in focus {except (1), Lively window}.
        ///(3) Foreground Process algorithm has some limitations, check wiki for more information.
        ///(4) Application Rules has the highest priority..
        /// </summary>
        public static string txtNotes {
            get {
                return ResourceManager.GetString("txtNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string txtOff {
            get {
                return ResourceManager.GetString("txtOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string txtOn {
            get {
                return ResourceManager.GetString("txtOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Application Focused:.
        /// </summary>
        public static string txtOtherAppsFocus {
            get {
                return ResourceManager.GetString("txtOtherAppsFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Application Fullscreen:.
        /// </summary>
        public static string txtOtherAppsFullScreen {
            get {
                return ResourceManager.GetString("txtOtherAppsFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Algorithm:.
        /// </summary>
        public static string txtPauseAlgorith {
            get {
                return ResourceManager.GetString("txtPauseAlgorith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Failed.
        /// </summary>
        public static string txtPleaseWait {
            get {
                return ResourceManager.GetString("txtPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait.
        /// </summary>
        public static string txtPleaseWait2 {
            get {
                return ResourceManager.GetString("txtPleaseWait2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep this window in focus while processing..
        /// </summary>
        public static string txtPreviewWallpaperNote {
            get {
                return ResourceManager.GetString("txtPreviewWallpaperNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select previewclip/thumbnail file..
        /// </summary>
        public static string txtSelectPreviewThumb {
            get {
                return ResourceManager.GetString("txtSelectPreviewThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Wallpaper.
        /// </summary>
        public static string txtSetWallpaper {
            get {
                return ResourceManager.GetString("txtSetWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some wallpapers will not span across displays properly..
        /// </summary>
        public static string txtSpanWallpaperWarning {
            get {
                return ResourceManager.GetString("txtSpanWallpaperWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows:.
        /// </summary>
        public static string txtStartup {
            get {
                return ResourceManager.GetString("txtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure to uncheck this before uninstalling lively..
        /// </summary>
        public static string txtStartupToolTip {
            get {
                return ResourceManager.GetString("txtStartupToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string txtSupport {
            get {
                return ResourceManager.GetString("txtSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated GIF.
        /// </summary>
        public static string txtTileGIF {
            get {
                return ResourceManager.GetString("txtTileGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Godot Software.
        /// </summary>
        public static string txtTileGodot {
            get {
                return ResourceManager.GetString("txtTileGodot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string txtTileHTML {
            get {
                return ResourceManager.GetString("txtTileHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string txtTileOther {
            get {
                return ResourceManager.GetString("txtTileOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Software.
        /// </summary>
        public static string txtTileUnity {
            get {
                return ResourceManager.GetString("txtTileUnity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string txtTileVideo {
            get {
                return ResourceManager.GetString("txtTileVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string txtTileWebsite {
            get {
                return ResourceManager.GetString("txtTileWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lively Wallpaper System.
        /// </summary>
        public static string txtTitlebar {
            get {
                return ResourceManager.GetString("txtTitlebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent UI:.
        /// </summary>
        public static string txtTransparency {
            get {
                return ResourceManager.GetString("txtTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make lively window semi-transparent..
        /// </summary>
        public static string txtTransparencyToolTip {
            get {
                return ResourceManager.GetString("txtTransparencyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available Lively.
        /// </summary>
        public static string txtUpdateBanner {
            get {
                return ResourceManager.GetString("txtUpdateBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update. Try downloading the installer from.
        /// </summary>
        public static string txtUpdateDownloadErrorMsg {
            get {
                return ResourceManager.GetString("txtUpdateDownloadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Player:.
        /// </summary>
        public static string txtVideoPlayer {
            get {
                return ResourceManager.GetString("txtVideoPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directshow requires additionals plugins to be installed..
        /// </summary>
        public static string txtVideoPlayerToolTip {
            get {
                return ResourceManager.GetString("txtVideoPlayerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Scaling/Fit:.
        /// </summary>
        public static string txtVideoScaling {
            get {
                return ResourceManager.GetString("txtVideoScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallpaper Playback:.
        /// </summary>
        public static string txtWallpaperPlayback {
            get {
                return ResourceManager.GetString("txtWallpaperPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When on Battery Power:.
        /// </summary>
        public static string txtWhenBattery {
            get {
                return ResourceManager.GetString("txtWhenBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Display.
        /// </summary>
        public static string txtWindowTitleSelectDisplay {
            get {
                return ResourceManager.GetString("txtWindowTitleSelectDisplay", resourceCulture);
            }
        }
    }
}
